name: Runner Unico

on:
  # Solo cron y lanzamiento manual. (Quitamos push para evitar bucles)
  schedule:
    - cron: "*/30 * * * *"   # cada 30 minutos (ajustá si querés)
  workflow_dispatch: {}

# Garantiza que haya una sola ejecución a la vez
concurrency:
  group: runner-unico
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    # Evita re-ejecuciones disparadas por el propio bot
    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ⬇️ Aca van TUS pasos reales (lo que hacen tus jobs).
      # Ejemplos:
      # - name: Configurar Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      #
      # - name: Ejecutar script
      #   run: |
      #     node scripts/tu_tarea.js

      # ⚠️ Si NO necesitás commitear/pushear cambios al repo, NO agregues pasos de git.
