name: Runner Unico (Mercado AR)

on:
  # Corre cada 5 minutos y también lo podés lanzar a mano
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

# Evita ejecuciones solapadas
concurrency:
  group: runner-unico
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    # Defensivo: no reacciona al bot
    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ====== Ventana horaria de mercado (Argentina) ======
      - name: Market hour gate (AR)
        id: market
        shell: bash
        run: |
          # Mercado AR aprox. 11:00 a 17:30 (Buenos Aires)
          HOUR_MIN=$(TZ=America/Argentina/Buenos_Aires date +%H%M)
          echo "Hora local AR: $(TZ=America/Argentina/Buenos_Aires date)"

          if [[ "$HOUR_MIN" -ge "1100" && "$HOUR_MIN" -lt "1730" ]]; then
            echo "open=true" >> "$GITHUB_OUTPUT"
            echo "Mercado ABIERTO → ejecuto run.py"
          else
            echo "open=false" >> "$GITHUB_OUTPUT"
            echo "Mercado CERRADO → salgo sin hacer requests"
          fi

      - name: Skip outside market hours
        if: ${{ steps.market.outputs.open == 'false' }}
        run: |
          echo "Fuera de horario → finalizando en vacío."
          exit 0

      # ====== Python + dependencias ======
      - name: Setup Python
        if: ${{ steps.market.outputs.open == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        if: ${{ steps.market.outputs.open == 'true' }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar dependencias (si hay requirements.txt)
        if: ${{ steps.market.outputs.open == 'true' }}
        run: |
          if [ -f requirements.txt ]; then
            pip install -U pip
            pip install -r requirements.txt
          else
            echo "No hay requirements.txt; continuo."
          fi

      # ====== Ejecutar tu script ======
      - name: Run script
        if: ${{ steps.market.outputs.open == 'true' }}
        run: |
          python run.py
